### ISSUE TITLE
Font size issues in code blocks on mobile

### ISSUE THREAD

**Issue by xNaCly** [nodejh/hugo-theme-mini#130]
https://xnacly.github.io/blog/posts/2022/rss_parser/
mobile: 
![image](https://user-images.githubusercontent.com/47723417/184857152-e97ebfaa-1511-457a-b2e2-9b258d45336c.png)
PC: 
![image](https://user-images.githubusercontent.com/47723417/184857207-03541324-175a-4c38-81e8-3e7b0d3c8dd6.png)

Any way to fix this?

**Comment by xNaCly** [comment]
It should be noted that this issue only happens on ios devices due to safaris flex blox implementation changing font sizes

People facing the same issue can be helped by setting the following values on `code` elements:

```css
/* this should fix the ios mobile code blog font size bug
 * recorded here: https://github.com/adityatelange/hugo-PaperMod/issues/828 */
code {
	text-size-adjust: 100%;
	-ms-text-size-adjust: 100%;
	-moz-text-size-adjust: 100%;
	-webkit-text-size-adjust: 100%;
}
```
*Code taken from https://github.com/xNaCly/hugo-theme-mini/blob/master/static/css/style.css*

Fix found at: https://github.com/adityatelange/hugo-PaperMod/issues/828
